fix: test linter (html/css/js) (#9)

diff --git a/.github/workflows/lint-static.yml b/.github/workflows/lint-static.yml
--- a/.github/workflows/lint-static.yml
+++ b/.github/workflows/lint-static.yml
@@ -1,16 +1,7 @@
 name: 🦋 Lint static assets
 
 on:
-  push:
-    paths:
-      - "static/**.html"
-      - "static/**.css"
-      - "static/**.js"
-  pull_request:
-    paths:
-      - "static/**.html"
-      - "static/**.css"
-      - "static/**.js"
+  workflow_dispatch:
 
 jobs:
   lint:
@@ -28,14 +19,30 @@ jobs:
         run: |
           npm install -g htmlhint stylelint stylelint-config-standard eslint
 
-      - name: Lint HTML
+      - name: install dependencies
         run: |
-          htmlhint 'static/**/*.html' || exit 1
+          npm install
+
+      - name: Lint HTML
+        id: lint_html
+        continue-on-error: true
+        run: |
+          npx htmlhint 'static/**/*.html'
 
       - name: Lint CSS
+        id: lint_css
+        continue-on-error: true
         run: |
-          stylelint 'static/**/*.css' --config '{"extends": "stylelint-config-standard"}' || exit 1
+          npx stylelint 'static/**/*.css' --config .stylelintrc.json
 
       - name: Lint JavaScript
+        id: lint_js
+        continue-on-error: true
         run: |
-          eslint 'static/**/*.js' --no-eslintrc --env browser --env es2021 || exit 1
+          npx eslint 'static/**/*.js'
+
+      - name: Fail if any linter failed
+        if: steps.lint_html.outcome == 'failure' || steps.lint_css.outcome == 'failure' || steps.lint_js.outcome == 'failure'
+        run: |
+          echo "One or more linters failed."
+          exit 1
